//FEEDBACK 
export const CREATE_FEEDBACK = "CREATE_FEEDBACK"
export const CREATE_FEEDBACK_RED = "CREATE_FEEDBACK_RED"
export const GET_FEEDBACK = "GET_FEEDBACK"
export const GET_FEEDBACK_RED = "GET_FEEDBACK_RED"
export const UPDATE_FEEDBACK = "UPDATE_FEEDBACK"
export const UPDATE_FEEDBACK_RED = "UPDATE_FEEDBACK_RED"
export const DELETE_FEEDBACK = "DELETE_FEEDBACK"
export const DELETE_FEEDBACK_RED = "DELETE_FEEDBACK_RED"

